name: infinite_gallery
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.4
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  hive: ^2.0.6
  hive_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  hive_generator: 
  build_runner: 
  bloc_test: ^9.0.2
  mockito: ^5.0.17
  mocktail: ^0.2.0
  http_mock_adapter: ^0.3.2

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
